### ISSUE TITLE
Required version: 100, found 102

### ISSUE THREAD

**Issue by anil-sezer** [ChthonVII/CnC_Remastered_Collection#1]
Hi! 
Is there anyone who managed to get any release of this mod with Red Alert version 1.153?

I'm always getting this error. How can I resolve this?

![delete this ss](https://github.com/ChthonVII/CnC_Remastered_Collection/assets/54420725/0d0b1b14-4950-4e58-a3e5-512274bc1656)

**Comment by ChthonVII** [comment]
It looks like you're trying to make this mod work with a pirate version of the game older than the 9/16/2020 patch. I'm not going to pretend to be aghast at piracy, but I'm not inclined to go to great lengths to help you either.

The API was changed in that patch, so of course a mod using the newer API isn't going to work on an older version of the game. In order to make it work, you'd need to check out the the vanilla source from before that patch, and then rebase this mod on top of that.

**Comment by ChthonVII** [comment]
(correct close reason)

**Comment by anil-sezer** [comment]
As a fan of Dawn of The Tiberium Age, I got a strong opinnion that C&C Remastered should be pirated as it offers so little effort. Shame on them. 
Thank you. I searched much and thought I had the latest patch. 
Have a nice day
